### ISSUE TITLE
Program Running exit on DA14531 PRO-devkit

### ISSUE THREAD

**Issue by TK-HHY** [stawiski/da14531-cmake-template#1]
Hi,

Thank you for your solution really helpful.
I'm figuring a problem running on DA14531, the program exit with ExternalIRQ Exception and disassembly XTAL32_RDY_handler.
Any Ideo on why this problem?

Thank you,

Tony Wilson

**Comment by blauret** [comment]
Hi Tony, 

For reference, the cmake implementation (from here) is available in the example from from Renesas (ex Dialog).

You could try one of the example [there](https://github.com/dialog-semiconductor/BLE_SDK6_examples). If you're still facing issues I would suggest to open a ticket on that repository as Renesas team is monitoring that and answering questions.

**Comment by TK-HHY** [comment]
Hi Blauret,

Ok, I will try this.

Thank you
